### ISSUE TITLE
Primeiros passos com NodeJS

### ISSUE THREAD

**Issue by SylvioMigliorucci** [backend-br/newsletter#3]
https://tableless.com.br/o-que-nodejs-primeiros-passos-com-node-js/

**Comment by Kirmayrtomaz** [comment]
Esse artigo é de 2014, e a versão de exemplo é a 0.10. 
Será que vale a pena colocar?

**Comment by SylvioMigliorucci** [comment]
Desculpe, vou procurar por um artigo com versão mais atual.
